### ISSUE TITLE
Favicon

### ISSUE THREAD

**Issue by lightdiscord** [lightdiscord/arnaud.sh#10]

**Comment by richardbmx** [comment]
@LightDiscord  Hi, my name is Richard. I'm a graphic designer and I love making contributions for open source projects. I see that they want a new Favicon for your application. If you wish, I can do it for you without any problem ... I can present some modern ideas that would improve the appearance and image of your project

**Comment by LightDiscord** [comment]
It's very nice to offer that, but I was planning on putting my avatar as the favicon of my portfolio. :smile:
